# Copyright The Kubeform Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:stretch

RUN apt-get update \
  && apt-get -y install curl \
  && apt-get -y install unzip \
  && curl -O -L https://releases.hashicorp.com/terraform/0.12.4/terraform_0.12.4_linux_amd64.zip \
  && unzip terraform_0.12.4_linux_amd64.zip \
  && mv terraform /bin/terraform



FROM {ARG_FROM}

COPY bin/{ARG_OS}_{ARG_ARCH}/{ARG_BIN} /{ARG_BIN}
COPY --from=0 /bin/terraform /bin/terraform

# This would be nicer as `nobody:nobody` but distroless has no such entries.
USER 65535:65535

ENTRYPOINT ["/{ARG_BIN}"]
